Repository boostcampwm2023/web07-GBS, pull requests merged in 2023-11, with the labels that each got.

#4 [feat] Nest 초기 설치
  .idea/.gitignore
  .idea/modules.xml
  .idea/vcs.xml
  .idea/web07-GBS.iml
  server/api-server/.eslintrc.js
  server/api-server/.gitignore
  server/api-server/.prettierrc
  server/api-server/README.md
  server/api-server/nest-cli.json
  server/api-server/package.json
  server/api-server/src/app.controller.spec.ts
  server/api-server/src/app.controller.ts
  server/api-server/src/app.module.ts
  server/api-server/src/app.service.ts
  server/api-server/src/main.ts
  server/api-server/test/app.e2e-spec.ts
  server/api-server/test/jest-e2e.json
  server/api-server/tsconfig.build.json
  server/api-server/tsconfig.json
  server/api-server/yarn.lock
Labels: BE, chore

#2 [feat] 프론트엔드 프로젝트 세팅
  client/.eslintrc.cjs
  client/.gitignore
  client/.prettierignore
  client/.prettierrc
  client/.storybook/main.ts
  client/.storybook/preview.ts
  client/README.md
  client/index.html
  client/package.json
  client/public/vite.svg
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/components/hls/index.tsx
  client/src/main.tsx
  client/src/stories/Button.stories.ts
  client/src/stories/Button.tsx
  client/src/stories/button.css
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  client/yarn.lock
Labels: FE, chore

#6 [chore] API 서버 CI/CD
  .github/workflows/deploy.yml
  server/api-server/Dockerfile
Labels: BE, chore

#10 [feat] 스트리밍/인코딩 서버 세팅 및 송수신 구현
  .github/workflows/deploy.yml
  server/api-server/yarn.lock
  server/encoding-server/.gitignore
  server/encoding-server/Dockerfile
  server/encoding-server/app.js
  server/encoding-server/package-lock.json
  server/encoding-server/package.json
  server/rtmp-server/.gitignore
  server/rtmp-server/Dockerfile
  server/rtmp-server/app.js
  server/rtmp-server/package-lock.json
  server/rtmp-server/package.json
Labels: BE, feat

#14 [fix] CI/CD 수정
  .github/workflows/deploy.yml
  server/encoding-server/Dockerfile
  server/rtmp-server/Dockerfile
Labels: BE, fix

#21 [feat] 프론트엔드 라우터 세팅
  client/package.json
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/ExPage/ExPage.styles.tsx
  client/src/pages/ExPage/ExPage.tsx
  client/src/pages/HomePage/HomePage.styles.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/yarn.lock
Labels: FE, feat

#23 [feat] 인코딩 서버 구현
  .github/workflows/deploy.yml
  server/encoding-server/.gitignore
  server/encoding-server/Dockerfile
  server/encoding-server/app.js
  server/encoding-server/package-lock.json
  server/encoding-server/package.json
Labels: BE, feat

#27 [chore] 프론트엔드 절대경로 설정
  client/tsconfig.json
  client/vite.config.ts
Labels: FE, chore

#30 [fix] H264 화면 송출 에러 수정
  .github/workflows/deploy.yml
  server/rtmp-server/Dockerfile
  server/rtmp-server/app.js
  server/rtmp-server/node_relay_session.js
Labels: BE, fix

#31 [feat] 2-1 화면 구성
  client/src/App.tsx
  client/src/assets/images/box-logo.svg
  client/src/assets/images/wide-logo.svg
  client/src/components/Access/Access.styles.tsx
  client/src/components/Access/Access.tsx
  client/src/components/Chatting/Chatting.styles.tsx
  client/src/components/Chatting/Chatting.tsx
  client/src/components/HlsPlayer/HlsPlayer.tsx
  client/src/components/Logo/Logo.styles.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/Modal/LoginModal/LoginModal.styles.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/components/Modal/RegisterModal/RegisterModal.styles.tsx
  client/src/main.tsx
  client/src/pages/BroadcastPage/BroadcastPage.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/stories/Button.tsx
  client/src/stories/button.css
  client/src/styles/GlobalStyles.styles.tsx
  client/src/styles/typo/TYPO.ts
Labels: FE, feat

#34 [feat] 반응형 웹 디자인 구현
  client/src/pages/BroadcastPage/BroadcastPage.styles.tsx
  client/src/styles/GlobalStyles.styles.tsx
  client/src/styles/typo/TYPO.ts
Labels: FE, feat

#36 [feat] 방송 화면 모달창과 연동
  client/src/components/Access/Access.tsx
  client/src/components/Modal/LoginModal/LoginModal.styles.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/components/Modal/RegisterModal/RegisterModal.styles.tsx
  client/src/components/Modal/RegisterModal/RegisterModal.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/styles/typo/TYPO.ts
Labels: FE, feat

#39 [fix] 채팅창 오류 수정
  client/src/components/Chatting/Chatting.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
Labels: FE, fix

#46 [Feat] 스트리밍 서버 nginx-rtmp-module로 변경
  server/rtmp-server/.gitignore
  server/rtmp-server/Dockerfile
  server/rtmp-server/app.js
  server/rtmp-server/nginx.conf
  server/rtmp-server/node_relay_session.js
  server/rtmp-server/package-lock.json
  server/rtmp-server/package.json
  server/rtmp-server/run.sh
Labels: BE, feat

#48 [feat] 프론트 CI/CD 구축하기
  .github/workflows/deploy.yml
  client/Dockerfile
  client/src/styles/typo/Pretendard.tsx
Labels: FE, feat

#47 [feat] 1-1 메인 화면 구성
  client/src/App.tsx
  client/src/components/Access/Access.styles.tsx
  client/src/components/Access/Access.tsx
  client/src/components/Broadcast/Broadcast.styles.tsx
  client/src/components/Broadcast/Broadcast.tsx
  client/src/components/Chatting/Chatting.styles.tsx
  client/src/components/Chatting/Chatting.tsx
  client/src/components/Logo/Logo.tsx
  client/src/main.tsx
  client/src/pages/BroadcastPage/BroadcastPage.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/ExPage/ExPage.styles.tsx
  client/src/pages/ExPage/ExPage.tsx
  client/src/pages/HomePage/HomePage.styles.tsx
  client/src/pages/HomePage/HomePage.tsx
  client/src/pages/MainPage/MainPage.styles.tsx
  client/src/pages/MainPage/MainPage.tsx
Labels: FE, feat

#55 [feat] TypeORM 연관관계 매핑
  .github/workflows/deploy.yml
  server/api-server/package-lock.json
  server/api-server/package.json
  server/api-server/sql/schema.sql
  server/api-server/src/app.module.ts
  server/api-server/src/streams/dto/create-stream.dto.ts
  server/api-server/src/streams/dto/update-stream.dto.ts
  server/api-server/src/streams/entities/stream.entity.ts
  server/api-server/src/streams/streams.controller.spec.ts
  server/api-server/src/streams/streams.controller.ts
  server/api-server/src/streams/streams.module.ts
  server/api-server/src/streams/streams.service.spec.ts
  server/api-server/src/streams/streams.service.ts
  server/api-server/src/users/dto/create-user.dto.ts
  server/api-server/src/users/dto/update-user.dto.ts
  server/api-server/src/users/entities/user.entity.ts
  server/api-server/src/users/users.controller.spec.ts
  server/api-server/src/users/users.controller.ts
  server/api-server/src/users/users.module.ts
  server/api-server/src/users/users.service.spec.ts
  server/api-server/src/users/users.service.ts
  server/api-server/yarn.lock
Labels: BE, feat

#53 [feat] 프론트 CI/CD 배포 오류 수정
  client/Dockerfile
  client/index.html
  client/public/assets/images/box-logo.svg
  client/public/assets/images/wide-logo.svg
  client/public/assets/react.svg
  client/public/vite.svg
  client/src/components/Logo/Logo.tsx
  client/tsconfig.json
Labels: FE, fix

#56 [feat] 사용자 클릭 기능 구현
  client/src/components/Chatting/Chatting.styles.tsx
  client/src/components/Chatting/Chatting.tsx
  client/src/components/Modal/LoginModal/LoginModal.styles.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/components/Modal/RegisterModal/RegisterModal.styles.tsx
  client/src/components/Modal/RegisterModal/RegisterModal.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.styles.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.tsx
Labels: FE, feat

#59 [docs] README.md 보완하기
  README.md
Labels: docs

#62 [fix] 스트리머 ID가 나오지 않는 오류 수정
  client/src/components/Modal/ViewerModal/ViewerModal.styles.tsx
  client/src/pages/MainPage/MainPage.tsx
Labels: FE, fix

#66 [feat] 엔터키로 채팅 보내는 기능 구현
  client/src/pages/BroadcastPage/BroadcastPage.tsx
Labels: FE, feat

#63 [feat] 스트리밍 서버 - 동영상 정보 조회 기능 추가
  .github/workflows/deploy.yml
  server/api-server/Dockerfile
  server/rtmp-server/Dockerfile
  server/rtmp-server/nginx.conf
Labels: BE, feat

#67 [feat] 다크모드 만들기
  client/src/App.tsx
  client/src/components/Broadcast/Broadcast.styles.tsx
  client/src/components/ThemeSwitch/ThemeSwitch.styles.tsx
  client/src/components/ThemeSwitch/ThemeSwitch.tsx
  client/src/main.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/state/theme.ts
  client/src/styles/GlobalStyles.styles.tsx
  client/src/styles/theme.ts
Labels: FE, feat

#70 [feat] 방송 정보 CRUD API 구현
  server/api-server/src/common/dto/page.dto.ts
  server/api-server/src/streams/dto/create-stream.dto.ts
  server/api-server/src/streams/dto/read-stream-detail.dto.ts
  server/api-server/src/streams/dto/read-stream.dto.ts
  server/api-server/src/streams/dto/update-stream.dto.ts
  server/api-server/src/streams/dto/video-info.dto.ts
  server/api-server/src/streams/entities/stream.entity.ts
  server/api-server/src/streams/provider/video-info.provider.ts
  server/api-server/src/streams/streams.controller.ts
  server/api-server/src/streams/streams.module.ts
  server/api-server/src/streams/streams.service.ts
  server/api-server/src/users/entities/user.entity.ts
  server/api-server/src/users/users.module.ts
Labels: BE, feat

#74 [feat] 채팅 기능 구현
  client/package.json
  client/src/components/Chatting/Chatting.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/yarn.lock
  server/chatting-server/.gitignore
  server/chatting-server/package.json
  server/chatting-server/src/index.ts
  server/chatting-server/tsconfig.json
  server/chatting-server/yarn.lock
Labels: BE, FE, feat

#75 [feat] 다크모드 보완 및 CI/CD 오류 해결
  client/public/assets/images/box-logo-white.svg
  client/public/assets/images/wide-logo-white.svg
  client/src/App.tsx
  client/src/components/Broadcast/Broadcast.styles.tsx
  client/src/components/Broadcast/Broadcast.tsx
  client/src/components/Logo/Logo.tsx
  client/src/pages/BroadcastPage/BroadcastPage.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.styles.tsx
  client/src/pages/MainPage/MainPage.tsx
Labels: FE, feat

#71 [feat] 로그인, 회원가입 API 설계 및 구현
  server/api-server/.gitignore
  server/api-server/Dockerfile
  server/api-server/package.json
  server/api-server/src/app.controller.ts
  server/api-server/src/app.module.ts
  server/api-server/src/auth/auth.controller.ts
  server/api-server/src/auth/auth.module.ts
  server/api-server/src/auth/auth.service.ts
  server/api-server/src/auth/guard/logged-in.guard.ts
  server/api-server/src/auth/guard/naver-auth.guard.ts
  server/api-server/src/auth/strategy/naver.strategy.ts
  server/api-server/src/init.session.ts
  server/api-server/src/main.ts
  server/api-server/src/users/dto/create-user.dto.ts
  server/api-server/src/users/entities/user.entity.ts
  server/api-server/src/users/users.controller.ts
  server/api-server/src/users/users.module.ts
  server/api-server/src/users/users.service.ts
  server/api-server/yarn.lock
Labels: BE, feat

#83 [fix] 다크모드 변경 시 채팅창 배경색 변경
  client/src/components/Modal/LoginModal/LoginModal.stories.tsx
  client/src/components/Modal/LoginModal/LoginModal.styles.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/components/Modal/RegisterModal/Register.stories.tsx
  client/src/components/Modal/RegisterModal/RegisterModal.styles.tsx
  client/src/components/Modal/RegisterModal/RegisterModal.tsx
  client/src/pages/BroadcastPage/BroadcastPage.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.tsx
Labels: FE, fix

#79 [fix] redis 연결, 로그인&회원가입완료
  server/api-server/Dockerfile
  server/api-server/package.json
  server/api-server/src/auth/auth.controller.ts
  server/api-server/src/auth/auth.service.ts
  server/api-server/src/auth/strategy/naver.strategy.ts
  server/api-server/src/init.session.ts
  server/api-server/src/streams/streams.module.ts
  server/api-server/src/users/dto/update-user.dto.ts
  server/api-server/src/users/entities/user.entity.ts
  server/api-server/src/users/users.controller.ts
  server/api-server/src/users/users.module.ts
  server/api-server/src/users/users.service.ts
  server/api-server/yarn.lock
Labels: BE, fix

#80 [feat] NestJS 채팅 서버 구현
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  server/api-server/.eslintrc.js
  server/api-server/.prettierrc
  server/api-server/package-lock.json
  server/api-server/package.json
  server/api-server/src/app.controller.ts
  server/api-server/src/app.module.ts
  server/api-server/src/auth/auth.controller.ts
  server/api-server/src/auth/strategy/naver.strategy.ts
  server/api-server/src/chat/chat.gateway.ts
  server/api-server/src/chat/chat.module.ts
  server/api-server/src/chat/dto/chat-payload.ts
  server/api-server/src/chat/dto/join-payload.dto.ts
  server/api-server/src/init.session.ts
  server/api-server/yarn.lock
  server/chatting-server/.gitignore
  server/chatting-server/package.json
  server/chatting-server/src/index.ts
  server/chatting-server/tsconfig.json
  server/chatting-server/yarn.lock
Labels: BE, feat

#88 [refactor] ID, 닉네임과 관련된 변수명 변경
  client/src/components/Broadcast/Broadcast.styles.tsx
  client/src/components/Broadcast/Broadcast.tsx
  client/src/components/Chatting/Chatting.styles.tsx
  client/src/components/Chatting/Chatting.tsx
  client/src/components/Modal/LoginModal/LoginModal.styles.tsx
  client/src/components/Modal/RegisterModal/RegisterModal.styles.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.stories.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.styles.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.tsx
  client/src/pages/BroadcastPage/BroadcastPage.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/types/theme.ts
Labels: FE, refactor

#90 [feat] useApi 커스텀 훅 제작
  client/.gitignore
  client/src/hooks/useApi.ts
Labels: FE, feat

#93 [feat] 채팅 서버 Redis Pub/Sub 연결
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  server/api-server/package.json
  server/api-server/src/chat/chat.gateway.spec.ts
  server/api-server/src/chat/chat.gateway.ts
  server/api-server/src/chat/chat.module.ts
  server/api-server/src/chat/dto/chat-payload.ts
  server/api-server/src/init.session.ts
  server/api-server/src/main.ts
  server/api-server/src/redis.adapter.ts
  server/api-server/src/redis.session.ts
  server/api-server/src/streams/streams.module.ts
  server/api-server/src/streams/streams.service.ts
  server/api-server/src/users/users.controller.ts
  server/api-server/src/users/users.service.ts
  server/api-server/yarn.lock
Labels: BE, feat

#94 [feat] 네이버 간편로그인 연동
  client/index.html
  client/public/images/box-logo-dark.svg
  client/public/images/box-logo-light.svg
  client/public/images/naver-login.png
  client/public/images/wide-logo-dark.svg
  client/public/images/wide-logo-light.svg
  client/src/components/Logo/Logo.tsx
  client/src/components/Modal/LoginModal/LoginModal.styles.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/components/Modal/RegisterModal/RegisterModal.styles.tsx
  client/src/components/Modal/RegisterModal/RegisterModal.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.styles.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.tsx
Labels: FE, feat

#95 [feat] user api 구현완료, 환경변수 분리
  .gitignore
  .idea/vcs.xml
  client/src/components/Access/Access.tsx
  client/src/components/Modal/LoginModal/LoginModal.styles.tsx
  server/api-server/.gitignore
  server/api-server/docker-compose.yaml
  server/api-server/package.json
  server/api-server/src/app.module.ts
  server/api-server/src/auth/auth.controller.ts
  server/api-server/src/users/dto/update-user.dto.ts
  server/api-server/src/users/users.controller.spec.ts
  server/api-server/testMysql/Dockerfile
  server/api-server/testMysql/docker/mysql/init-test-db.sql
  server/api-server/yarn.lock
Labels: BE, feat

#104 [design] 회원가입을 환경설정으로 수정
  client/src/components/Access/Access.tsx
  client/src/components/Modal/LoginModal/LoginModal.styles.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/components/Modal/RegisterModal/RegisterModal.tsx
  client/src/components/Modal/SettingModal/SettingModal.stories.tsx
  client/src/components/Modal/SettingModal/SettingModal.styles.tsx
  client/src/components/Modal/SettingModal/SettingModal.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.styles.tsx
  client/src/components/ThemeSwitch/ThemeSwitch.styles.tsx
  client/src/components/ThemeSwitch/ThemeSwitch.tsx
  client/src/pages/BroadcastPage/BroadcastPage.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.tsx
Labels: FE, design

#106 [feat] : https 연결을 위한 deploy.yml 변경
  .github/workflows/deploy.yml
Labels: feat

#110 [refactor] Socket을 여러 번 불러오는 오류 수정
  .github/workflows/deploy.yml
  client/.eslintrc.cjs
  client/src/components/Modal/SettingModal/SettingModal.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.tsx
Labels: FE, refactor
