Repository boostcampwm2023/web07-GBS, pull requests merged in 2023-12, with the labels that each got.

#107 [feat] RTMP 서버 StreamKey 필터링
  .github/workflows/deploy-api-server.yml
  .github/workflows/deploy-front.yml
  .github/workflows/deploy-rtmp-server.yml
  .github/workflows/deploy.yml
  server/api-server/src/app.module.ts
  server/api-server/src/common/middleware/logger.middleware.ts
  server/api-server/src/common/redis.adapter.ts
  server/api-server/src/common/redis.session.ts
  server/api-server/src/main.ts
  server/api-server/src/streams/dto/verify-stream-key.dto.ts
  server/api-server/src/streams/stream-keys.controller.ts
  server/api-server/src/streams/streams.module.ts
  server/api-server/src/streams/streams.service.ts
  server/rtmp-server/nginx.conf
  server/rtmp-server/run.sh
Labels: BE, feat

#113 [feat] user api 완성, login guard 전역 설정
  server/api-server/package.json
  server/api-server/src/auth/auth.controller.ts
  server/api-server/src/auth/auth.service.ts
  server/api-server/src/auth/guard/logged-in.guard.ts
  server/api-server/src/common/redis.session.ts
  server/api-server/src/main.ts
  server/api-server/src/streams/streams.controller.ts
  server/api-server/src/users/users.controller.spec.ts
  server/api-server/src/users/users.controller.ts
  server/api-server/src/users/users.module.ts
  server/api-server/src/users/users.service.ts
  server/api-server/yarn.lock
Labels: BE, feat

#117 [feat] 유저 전역상태 만들기 & 로그인 하지 않은사람 채팅 막기
  client/src/components/Modal/ConfirmModal/ConfirmModal.styles.tsx
  client/src/components/Modal/ConfirmModal/ConfirmModal.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/states/user.ts
  client/src/types/user.ts
Labels: FE, feat

#118 [feat] docker-compose 로컬 테스트 환경 구축
  .github/workflows/deploy-front.yml
  client/Dockerfile
  docker-compose.yml
  server/rtmp-server/Dockerfile
Labels: BE, feat

#120 [fix] https 설정
  .github/workflows/deploy-api-server.yml
  .gitignore
  server/api-server/Dockerfile
  server/api-server/docker-compose.yaml
  server/api-server/src/auth/auth.controller.ts
  server/api-server/src/auth/auth.module.ts
  server/api-server/src/auth/auth.service.ts
  server/api-server/src/auth/guard/logged-in.guard.ts
  server/api-server/src/auth/strategy/naver.strategy.ts
  server/api-server/src/main.ts
Labels: BE, fix

#126 [fix] 방송 정보를 가져오지 못하는 버그 수정
  server/rtmp-server/nginx.conf
Labels: BE, fix

#124 [fix] HTTPS 적용 후 채팅 안되는 문제 해결
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  server/api-server/src/auth/strategy/naver.strategy.ts
  server/api-server/src/chat/chat.gateway.ts
  server/api-server/src/main.ts
Labels: BE, fix

#129 [feat] 로그인 되었는지 확인하는 기능 구현
  client/src/App.tsx
  client/src/components/Broadcast/Broadcast.styles.tsx
  client/src/components/EmptyList/EmptyList.styles.tsx
  client/src/components/EmptyList/EmptyList.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/Modal/ConfirmModal/ConfirmModal.styles.tsx
  client/src/components/Modal/ConfirmModal/ConfirmModal.tsx
  client/src/components/Modal/LoginModal/LoginModal.stories.tsx
  client/src/components/Modal/LoginModal/LoginModal.styles.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/components/Modal/SettingModal/SettingModal.styles.tsx
  client/src/components/Modal/SettingModal/SettingModal.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.stories.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.styles.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.tsx
  client/src/hooks/useStoredTheme.ts
  client/src/pages/BroadcastPage/BroadcastPage.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.styles.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/states/theme.ts
  client/src/states/user.ts
  client/src/types/theme.ts
  server/api-server/package.json
  server/api-server/src/common/redis.session.ts
  server/api-server/src/main.ts
Labels: FE, feat

#132 [fix] RTMP 모듈에서 HTTPS를 지원하지 않아 발생한 문제 해결
  server/api-server/package.json
  server/api-server/src/main.ts
Labels: BE, fix

#128 [feat] streamkey 반환
  server/api-server/src/auth/strategy/naver.strategy.ts
  server/api-server/src/main.ts
  server/api-server/src/streams/stream-keys.controller.ts
  server/api-server/src/streams/streams.controller.ts
  server/api-server/src/streams/streams.service.ts
  server/api-server/src/users/users.controller.ts
  server/api-server/src/users/users.service.ts
Labels: BE, feat

#134 [fix] WebSocket 에러 반환 시 서버 꺼지는 문제 해결
  docker-compose.yml
  server/api-server/package.json
  server/api-server/src/chat/chat.gateway.ts
  server/api-server/src/main.ts
Labels: BE, fix

#136 [fix] 새로고침 시 404 해결 & 메인 화면 방송 리스트 api 연결
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.tsx
Labels: FE

#138 [feat] : 프론트 컨플릭트 이슈 해결
  client/src/pages/BroadcastPage/BroadcastPage.tsx
Labels: FE, fix

#140 [fix] StreamKey 감추기, 오타 수정
  server/api-server/.eslintrc.js
  server/api-server/src/main.ts
  server/api-server/src/streams/streams.service.ts
Labels: BE, fix

#152 [fix] 환경변수 수정
  .github/workflows/deploy-front.yml
Labels: FE, fix

#149 [feat] 썸네일 만들기
  .gitignore
  docker-compose.yml
  server/api-server/package.json
  server/api-server/src/app.module.ts
  server/api-server/src/streams/dto/read-stream-detail.dto.ts
  server/api-server/src/streams/dto/read-stream.dto.ts
  server/api-server/src/streams/provider/video-info.provider.ts
  server/api-server/src/streams/streams.module.ts
  server/api-server/src/streams/streams.service.ts
  server/api-server/src/thumbnails/s3.ts
  server/api-server/src/thumbnails/thumbnails.controller.ts
  server/api-server/src/thumbnails/thumbnails.module.ts
  server/api-server/src/thumbnails/thumbnails.service.ts
  server/api-server/yarn.lock
  server/encoding-server/nginx.conf
Labels: BE, feat

#158 [fix] 방송 제목 예외처리 및 말줄임표 적용
  client/src/components/Broadcast/Broadcast.styles.tsx
  client/src/components/Broadcast/Broadcast.tsx
  client/src/components/Chatting/Chatting.styles.tsx
  client/src/components/Chatting/Chatting.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/components/Modal/SettingModal/SettingModal.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.tsx
Labels: FE, fix

#159 [feat] AI 채팅 검열 구현
  server/api-server/package.json
  server/api-server/src/chat/chat.gateway.ts
  server/api-server/src/chat/chat.module.ts
  server/api-server/src/chat/dto/ai-chat-payload.dto.ts
  server/api-server/src/chat/dto/chat-payload.dto.ts
  server/api-server/src/chat/util/ai-chat-filter.spec.ts
  server/api-server/src/chat/util/ai-chat-filter.ts
Labels: BE, feat

#164 [fix] m3u8 확장자 누락 해결
  client/src/components/HlsPlayer/HlsPlayer.tsx
Labels: FE, fix

#165 [feat] 방송 목록이나 정보 조회 실패시 모달창을 띄우고 새로고침 하는 기능 구현
  client/Dockerfile
  client/src/components/Modal/ConfirmModal/ConfirmModal.styles.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/components/Modal/SettingModal/SettingModal.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.tsx
Labels: FE, feat

#167 [fix] 방송 제목을 제대로 못가져오는 오류 수정
  client/src/pages/MainPage/MainPage.tsx
Labels: FE, fix

#172 [feat] 매니저 삭제 및 강퇴 기능 구현
  client/src/components/HlsPlayer/HlsPlayer.styles.tsx
  client/src/components/HlsPlayer/HlsPlayer.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.stories.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.tsx
  server/api-server/src/chat/chat.gateway.ts
  server/api-server/src/chat/dto/kick-payload.dto.ts
Labels: BE, FE, feat

#176 [fix] AuthModule에 누락된 GoogleStrategy 추가
  server/api-server/src/auth/auth.module.ts
Labels: BE, fix

#177 [feat] 클라이언트 - 구글 로그인 구현
  client/src/components/Modal/LoginModal/LoginModal.tsx
Labels: FE, feat

#182 [design] 로그인 이미지 수정
  client/public/images/google-login.png
  client/public/images/naver-login.png
  client/src/components/Modal/LoginModal/LoginModal.styles.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/pages/MainPage/MainPage.tsx
Labels: FE, design

#184 [fix] chatting 이름 표기 오류 해결
  server/api-server/src/auth/strategy/google.strategy.ts
  server/api-server/src/chat/chat.gateway.ts
Labels: BE, fix

#185 [design] 로그인 디자인 변경
  client/public/images/google-login.png
  client/public/images/naver-login.png
  client/src/components/Chatting/Chatting.styles.tsx
  client/src/components/Modal/LoginModal/LoginModal.styles.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
Labels: FE, design

#187 [fix] 강퇴가 안되는 오류 수정
  client/src/components/Chatting/Chatting.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
Labels: FE, fix

#194 [feat] AI 필터를 껐다 켰다 하는 기능 구현
  client/src/components/Access/Access.tsx
  client/src/components/Chatting/Chatting.styles.tsx
  client/src/components/Modal/SettingModal/SettingModal.styles.tsx
  client/src/components/Modal/SettingModal/SettingModal.tsx
  client/src/pages/BroadcastPage/BroadcastPage.styles.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/states/filter.ts
  client/src/states/user.ts
  client/src/types/user.ts
  server/api-server/src/chat/chat.gateway.ts
  server/api-server/src/chat/dto/chat-payload.dto.ts
Labels: BE, FE, feat

#198 [design] 환경 설정 모달창 디자인 변경
  README.md
  client/src/components/Modal/SettingModal/SettingModal.tsx
Labels: FE, design

#206 [docs] README.md 파일 수정
  README.md
Labels: docs, other

#208 [fix] thumbnail url 수정
  server/api-server/src/thumbnails/thumbnails.service.ts
Labels: BE, fix

#210 [feat] 모달창 애니메이션 추가
  client/src/components/Modal/ConfirmModal/ConfirmModal.styles.tsx
  client/src/components/Modal/ConfirmModal/ConfirmModal.tsx
  client/src/components/Modal/LoginModal/LoginModal.styles.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/components/Modal/SettingModal/SettingModal.styles.tsx
  client/src/components/Modal/SettingModal/SettingModal.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.styles.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/types/modal.ts
Labels: FE, feat

#212 [fix] Storybook 오류 수정
  client/src/components/Modal/ConfirmModal/ConfirmModal.stories.tsx
Labels: FE, fix

#214 [feat] 채팅을 보내면 초점을 잃는 기능 추가
  client/src/components/HlsPlayer/HlsPlayer.tsx
  client/src/components/Modal/SettingModal/SettingModal.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/states/filter.ts
  client/src/states/theme.ts
Labels: FE, feat

#216 [fix] 채팅을 치고 나면 포커스를 잃는 오류 수정
  client/src/pages/BroadcastPage/BroadcastPage.tsx
Labels: FE, fix

#218 [fix] 방송 중에 ID 및 닉네임을 바꿀 수 없도록 수정
  client/src/components/Modal/SettingModal/SettingModal.tsx
  client/src/pages/BroadcastPage/BroadcastPage.tsx
  client/src/pages/MainPage/MainPage.tsx
  server/api-server/src/streams/streams.service.ts
Labels: FE, fix

#220 [fix] 채팅 오류 수정
  client/src/pages/BroadcastPage/BroadcastPage.tsx
Labels: FE, fix

#222 [fix] 모달창이 띄워져도 채팅이 입력되는 오류 수정
  client/src/pages/BroadcastPage/BroadcastPage.tsx
Labels: FE, fix

#224 [fix] 모달창이 떠있어도 엔터키가 입력되는 오류 수정
  client/src/pages/BroadcastPage/BroadcastPage.tsx
Labels: FE, fix

#227 [fix] user controller 수정
  server/api-server/src/users/users.controller.ts
Labels: BE, fix

#226 [docs] README.md 내용 추가
  README.md
Labels: docs, other

#231 [fix] 로그인 jwt 코드 제거
  server/api-server/package.json
  server/api-server/src/auth/auth.module.ts
  server/api-server/yarn.lock
Labels: BE, fix

#232 [fix] 스토리북 설명 수정
  client/src/components/Access/Access.tsx
  client/src/components/Chatting/Chatting.tsx
  client/src/components/HlsPlayer/HlsPlayer.tsx
  client/src/components/Logo/Logo.tsx
  client/src/components/Modal/LoginModal/LoginModal.tsx
  client/src/components/Modal/ViewerModal/ViewerModal.tsx
Labels: FE, fix

#233 [docs] README.md 노션 링크 변경
  README.md
  client/src/pages/MainPage/MainPage.styles.tsx
Labels: docs, other

#236 [docs] README.md 파일 수정
  README.md
Labels: docs, other
